source 'https://rubygems.org'
gem 'sinatra'
github 'sinatra/sinatra' do
  gem 'sinatra-contrib'
end
gem 'unicorn'
gem 'jbuilder'
gem 'mysql2'

group :development do
  gem 'shotgun', :group => :development
end

ruby '2.1.0'
